### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by riccardocescon** [MaikuB/myanimelist#6]
Hi, is it possible to migrate this package to null safety?
Sadly this is the only package that does not support null safety and it's causing issues with building the release

**Comment by riccardocescon** [comment]
> Hi, is it possible to migrate this package to null safety?
> Sadly this is the only package that does not support null safety and it's causing issues with building the release

@MaikuB any update?

**Comment by MaikuB** [comment]
No. It is open source so if you can migrate it yourself and submit a PR
